development:
  secret_key_base: 7b8164582a883ac7f4037701488127afa0c1502d817e511ad4952c36365aa1c449bf2305fab1b042be3f2bc6d07f162bb969f868fef37684db2e0eaadbfab7fb

test:
  secret_key_base: 299df4097ab60b1ad5182aa7b71b7360a6891256339658152866381b29a975697cf9859b99550a394526ea280b1fd7a7052977015b89ff31c05ce584ab040341

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
